name: "Build and publish"

on:
    push:
        branches:
            - release

jobs:
    release:
        name: publish
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: publish
              run: |
                  npm install
                  npm run lint
                  npm run test:unit
                  npm run test:e2e
                  npm run build
                  rm -R src/
                  rm -R .github/
                  rm -R .vscode/
                  rm -R .husky/
                  rm .eslintrc.cjs
                  rm .gitignore
                  rm commitlint.config.cjs
                  rm tsconfig.json
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
                  NODE_ENV: development
                  HUSKY: 0 # Disable Husky git hook installation
                  FAKEYOU_COOKIE: ${{secrets.FAKEYOU_COOKIE}}
